print('Hello!')
print('What is your name?')
# Use raw_input for python 2 and input for python 3
myName = raw_input()
print('It is good to meet you, ' + myName)
print('The length of your name is:')
print(len(myName))
print('What is your age?')
myAge = input()
print('You will be ' + str(int(myAge) + 1) + ' in a year.')
